name: dev-deploy
on: push

jobs:
  build-job:
    runs-on: ubuntu-24.04-arm
    container:
      image: golang:1.26
    steps:
      - uses: actions/checkout@v5
      - working-directory: src
        run: CGO_ENABLED=0 GOARCH=arm64 go build -tags lambda.norpc -o bootstrap main.go
  
  deploy-job:
    needs: build-job
    runs-on: ubuntu-24.04-arm
    container: 
      image: hashicorp/terraform
    steps:
      - uses: actions/checkout@v5
      - run: ls
      - working-directory: terraform
        run: | 
          terraform init
          terraform plan